server:
  port: 8081
spring:
  datasource:
    # 数据库连接信息
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/order
    username: root
    password: root
  h2:
    console:
      # 配置h2控制台路径：http://localhost:8081/h2-console
      path: /h2-console
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true